# Generated by Django 4.0.3 on 2022-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('categorie', models.CharField(choices=[('P', 'PetFood'), ('T', 'Toys')], default='P', max_length=1)),
            ],
        ),
    ]
